apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginx
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx
    spec:
      initContainers:
      - name: setup
        image: hellof20/go-mmproxy:v6
        command: [ "/bin/sh", "-c" ]
        args:
          - ip rule add from 127.0.0.1/8 iif lo table 123;
            ip route add local 0.0.0.0/0 dev lo table 123;
        securityContext:
          privileged: True
      containers:
      - name: go-mmproxy
        image: hellof20/go-mmproxy:v6
        command: ["/bin/sh", "-c" ]
        args:
          - /app/go-mmproxy -l 0.0.0.0:8080 -4 127.0.0.1:80
        securityContext:
          privileged: True
      - name: nginx
        image: nginx:1.13
        ports:
        - containerPort: 80
