apiVersion: v1
kind: Service
metadata:
  name: my-nginx-neg
  annotations:
    cloud.google.com/neg: '{"exposed_ports": {"8080":{"name": "my-nginx-neg"}}}'
spec:
  type: ClusterIP
  selector:
    app: nginx
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
